// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;

namespace Softsige.Ideias.EmailService.Core.Models
{
    public partial class LogEnvioEmail
    {
        public int LogEnvioEmailId { get; set; }
        public string EmailRemet { get; set; }
        public string EmailDest { get; set; }
        public string Assunto { get; set; }
        public string Mensagem { get; set; }
        public DateTime DataHoraEnvio { get; set; }
        public int? IdeiaId { get; set; }
        public int? AnaliseSeq { get; set; }
        public bool FgEmailEnviado { get; set; }        
    }
}